/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as ApiRazorpayWebhookRouteImport } from './routes/api/razorpay-webhook'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedPyqRouteImport } from './routes/_authenticated/pyq'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedCounselingRouteImport } from './routes/_authenticated/counseling'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCounselingIndexRouteImport } from './routes/_authenticated/counseling.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedTestsNewRouteImport } from './routes/_authenticated/tests.new'
import { Route as AuthenticatedTestAttemptIdRouteImport } from './routes/_authenticated/test.$attemptId'
import { Route as AuthenticatedSubjectSlugRouteImport } from './routes/_authenticated/subject.$slug'
import { Route as AuthenticatedReviewAttemptIdRouteImport } from './routes/_authenticated/review.$attemptId'
import { Route as AuthenticatedCounselingRoadmapRouteImport } from './routes/_authenticated/counseling.roadmap'
import { Route as AuthenticatedCounselingResourcesRouteImport } from './routes/_authenticated/counseling.resources'
import { Route as AuthenticatedCounselingPredictorRouteImport } from './routes/_authenticated/counseling.predictor'
import { Route as AuthenticatedCounselingExplorerRouteImport } from './routes/_authenticated/counseling.explorer'
import { Route as AuthenticatedCounselingCompareRouteImport } from './routes/_authenticated/counseling.compare'
import { Route as AuthenticatedCounselingChoiceFillingRouteImport } from './routes/_authenticated/counseling.choice-filling'
import { Route as AuthenticatedCounselingCalendarRouteImport } from './routes/_authenticated/counseling.calendar'
import { Route as AuthenticatedComingSoonFeatureRouteImport } from './routes/_authenticated/coming-soon.$feature'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminLegalRouteImport } from './routes/_authenticated/admin.legal'
import { Route as AuthenticatedAdminCounselingRouteImport } from './routes/_authenticated/admin.counseling'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin.billing'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as AuthenticatedAdminCounselingIndexRouteImport } from './routes/_authenticated/admin.counseling.index'
import { Route as AuthenticatedAdminContentIndexRouteImport } from './routes/_authenticated/admin.content.index'
import { Route as AuthenticatedCounselingResourcesSlugRouteImport } from './routes/_authenticated/counseling.resources.$slug'
import { Route as AuthenticatedCounselingCollegeIdRouteImport } from './routes/_authenticated/counseling.college.$id'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin.users.$id'
import { Route as AuthenticatedAdminCounselingReviewsRouteImport } from './routes/_authenticated/admin.counseling.reviews'
import { Route as AuthenticatedAdminCounselingEventsRouteImport } from './routes/_authenticated/admin.counseling.events'
import { Route as AuthenticatedAdminCounselingCutoffsRouteImport } from './routes/_authenticated/admin.counseling.cutoffs'
import { Route as AuthenticatedAdminCounselingArticlesRouteImport } from './routes/_authenticated/admin.counseling.articles'
import { Route as AuthenticatedAdminContentImportRouteImport } from './routes/_authenticated/admin.content.import'
import { Route as AuthenticatedAdminContentGenerateRouteImport } from './routes/_authenticated/admin.content.generate'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayWebhookRoute = ApiRazorpayWebhookRouteImport.update({
  id: '/api/razorpay-webhook',
  path: '/api/razorpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPyqRoute = AuthenticatedPyqRouteImport.update({
  id: '/pyq',
  path: '/pyq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCounselingRoute = AuthenticatedCounselingRouteImport.update({
  id: '/counseling',
  path: '/counseling',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCounselingIndexRoute =
  AuthenticatedCounselingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCounselingRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedTestsNewRoute = AuthenticatedTestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestAttemptIdRoute =
  AuthenticatedTestAttemptIdRouteImport.update({
    id: '/test/$attemptId',
    path: '/test/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectSlugRoute =
  AuthenticatedSubjectSlugRouteImport.update({
    id: '/subject/$slug',
    path: '/subject/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewAttemptIdRoute =
  AuthenticatedReviewAttemptIdRouteImport.update({
    id: '/review/$attemptId',
    path: '/review/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCounselingRoadmapRoute =
  AuthenticatedCounselingRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => AuthenticatedCounselingRoute,
  } as any)
const AuthenticatedCounselingResourcesRoute =
  AuthenticatedCounselingResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedCounselingRoute,
  } as any)
const AuthenticatedCounselingPredictorRoute =
  AuthenticatedCounselingPredictorRouteImport.update({
    id: '/predictor',
    path: '/predictor',
    getParentRoute: () => AuthenticatedCounselingRoute,
  } as any)
const AuthenticatedCounselingExplorerRoute =
  AuthenticatedCounselingExplorerRouteImport.update({
    id: '/explorer',
    path: '/explorer',
    getParentRoute: () => AuthenticatedCounselingRoute,
  } as any)
const AuthenticatedCounselingCompareRoute =
  AuthenticatedCounselingCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedCounselingRoute,
  } as any)
const AuthenticatedCounselingChoiceFillingRoute =
  AuthenticatedCounselingChoiceFillingRouteImport.update({
    id: '/choice-filling',
    path: '/choice-filling',
    getParentRoute: () => AuthenticatedCounselingRoute,
  } as any)
const AuthenticatedCounselingCalendarRoute =
  AuthenticatedCounselingCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedCounselingRoute,
  } as any)
const AuthenticatedComingSoonFeatureRoute =
  AuthenticatedComingSoonFeatureRouteImport.update({
    id: '/coming-soon/$feature',
    path: '/coming-soon/$feature',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLegalRoute = AuthenticatedAdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCounselingRoute =
  AuthenticatedAdminCounselingRouteImport.update({
    id: '/counseling',
    path: '/counseling',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCounselingIndexRoute =
  AuthenticatedAdminCounselingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCounselingRoute,
  } as any)
const AuthenticatedAdminContentIndexRoute =
  AuthenticatedAdminContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCounselingResourcesSlugRoute =
  AuthenticatedCounselingResourcesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCounselingResourcesRoute,
  } as any)
const AuthenticatedCounselingCollegeIdRoute =
  AuthenticatedCounselingCollegeIdRouteImport.update({
    id: '/college/$id',
    path: '/college/$id',
    getParentRoute: () => AuthenticatedCounselingRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminCounselingReviewsRoute =
  AuthenticatedAdminCounselingReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminCounselingRoute,
  } as any)
const AuthenticatedAdminCounselingEventsRoute =
  AuthenticatedAdminCounselingEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminCounselingRoute,
  } as any)
const AuthenticatedAdminCounselingCutoffsRoute =
  AuthenticatedAdminCounselingCutoffsRouteImport.update({
    id: '/cutoffs',
    path: '/cutoffs',
    getParentRoute: () => AuthenticatedAdminCounselingRoute,
  } as any)
const AuthenticatedAdminCounselingArticlesRoute =
  AuthenticatedAdminCounselingArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedAdminCounselingRoute,
  } as any)
const AuthenticatedAdminContentImportRoute =
  AuthenticatedAdminContentImportRouteImport.update({
    id: '/content/import',
    path: '/content/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentGenerateRoute =
  AuthenticatedAdminContentGenerateRouteImport.update({
    id: '/content/generate',
    path: '/content/generate',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/counseling': typeof AuthenticatedCounselingRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/pyq': typeof AuthenticatedPyqRoute
  '/search': typeof AuthenticatedSearchRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/counseling': typeof AuthenticatedAdminCounselingRouteWithChildren
  '/admin/legal': typeof AuthenticatedAdminLegalRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/coming-soon/$feature': typeof AuthenticatedComingSoonFeatureRoute
  '/counseling/calendar': typeof AuthenticatedCounselingCalendarRoute
  '/counseling/choice-filling': typeof AuthenticatedCounselingChoiceFillingRoute
  '/counseling/compare': typeof AuthenticatedCounselingCompareRoute
  '/counseling/explorer': typeof AuthenticatedCounselingExplorerRoute
  '/counseling/predictor': typeof AuthenticatedCounselingPredictorRoute
  '/counseling/resources': typeof AuthenticatedCounselingResourcesRouteWithChildren
  '/counseling/roadmap': typeof AuthenticatedCounselingRoadmapRoute
  '/review/$attemptId': typeof AuthenticatedReviewAttemptIdRoute
  '/subject/$slug': typeof AuthenticatedSubjectSlugRoute
  '/test/$attemptId': typeof AuthenticatedTestAttemptIdRoute
  '/tests/new': typeof AuthenticatedTestsNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/counseling/': typeof AuthenticatedCounselingIndexRoute
  '/admin/content/generate': typeof AuthenticatedAdminContentGenerateRoute
  '/admin/content/import': typeof AuthenticatedAdminContentImportRoute
  '/admin/counseling/articles': typeof AuthenticatedAdminCounselingArticlesRoute
  '/admin/counseling/cutoffs': typeof AuthenticatedAdminCounselingCutoffsRoute
  '/admin/counseling/events': typeof AuthenticatedAdminCounselingEventsRoute
  '/admin/counseling/reviews': typeof AuthenticatedAdminCounselingReviewsRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/counseling/college/$id': typeof AuthenticatedCounselingCollegeIdRoute
  '/counseling/resources/$slug': typeof AuthenticatedCounselingResourcesSlugRoute
  '/admin/content/': typeof AuthenticatedAdminContentIndexRoute
  '/admin/counseling/': typeof AuthenticatedAdminCounselingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/pyq': typeof AuthenticatedPyqRoute
  '/search': typeof AuthenticatedSearchRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/legal': typeof AuthenticatedAdminLegalRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/coming-soon/$feature': typeof AuthenticatedComingSoonFeatureRoute
  '/counseling/calendar': typeof AuthenticatedCounselingCalendarRoute
  '/counseling/choice-filling': typeof AuthenticatedCounselingChoiceFillingRoute
  '/counseling/compare': typeof AuthenticatedCounselingCompareRoute
  '/counseling/explorer': typeof AuthenticatedCounselingExplorerRoute
  '/counseling/predictor': typeof AuthenticatedCounselingPredictorRoute
  '/counseling/resources': typeof AuthenticatedCounselingResourcesRouteWithChildren
  '/counseling/roadmap': typeof AuthenticatedCounselingRoadmapRoute
  '/review/$attemptId': typeof AuthenticatedReviewAttemptIdRoute
  '/subject/$slug': typeof AuthenticatedSubjectSlugRoute
  '/test/$attemptId': typeof AuthenticatedTestAttemptIdRoute
  '/tests/new': typeof AuthenticatedTestsNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/counseling': typeof AuthenticatedCounselingIndexRoute
  '/admin/content/generate': typeof AuthenticatedAdminContentGenerateRoute
  '/admin/content/import': typeof AuthenticatedAdminContentImportRoute
  '/admin/counseling/articles': typeof AuthenticatedAdminCounselingArticlesRoute
  '/admin/counseling/cutoffs': typeof AuthenticatedAdminCounselingCutoffsRoute
  '/admin/counseling/events': typeof AuthenticatedAdminCounselingEventsRoute
  '/admin/counseling/reviews': typeof AuthenticatedAdminCounselingReviewsRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/counseling/college/$id': typeof AuthenticatedCounselingCollegeIdRoute
  '/counseling/resources/$slug': typeof AuthenticatedCounselingResourcesSlugRoute
  '/admin/content': typeof AuthenticatedAdminContentIndexRoute
  '/admin/counseling': typeof AuthenticatedAdminCounselingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/counseling': typeof AuthenticatedCounselingRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/pyq': typeof AuthenticatedPyqRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/counseling': typeof AuthenticatedAdminCounselingRouteWithChildren
  '/_authenticated/admin/legal': typeof AuthenticatedAdminLegalRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/coming-soon/$feature': typeof AuthenticatedComingSoonFeatureRoute
  '/_authenticated/counseling/calendar': typeof AuthenticatedCounselingCalendarRoute
  '/_authenticated/counseling/choice-filling': typeof AuthenticatedCounselingChoiceFillingRoute
  '/_authenticated/counseling/compare': typeof AuthenticatedCounselingCompareRoute
  '/_authenticated/counseling/explorer': typeof AuthenticatedCounselingExplorerRoute
  '/_authenticated/counseling/predictor': typeof AuthenticatedCounselingPredictorRoute
  '/_authenticated/counseling/resources': typeof AuthenticatedCounselingResourcesRouteWithChildren
  '/_authenticated/counseling/roadmap': typeof AuthenticatedCounselingRoadmapRoute
  '/_authenticated/review/$attemptId': typeof AuthenticatedReviewAttemptIdRoute
  '/_authenticated/subject/$slug': typeof AuthenticatedSubjectSlugRoute
  '/_authenticated/test/$attemptId': typeof AuthenticatedTestAttemptIdRoute
  '/_authenticated/tests/new': typeof AuthenticatedTestsNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/counseling/': typeof AuthenticatedCounselingIndexRoute
  '/_authenticated/admin/content/generate': typeof AuthenticatedAdminContentGenerateRoute
  '/_authenticated/admin/content/import': typeof AuthenticatedAdminContentImportRoute
  '/_authenticated/admin/counseling/articles': typeof AuthenticatedAdminCounselingArticlesRoute
  '/_authenticated/admin/counseling/cutoffs': typeof AuthenticatedAdminCounselingCutoffsRoute
  '/_authenticated/admin/counseling/events': typeof AuthenticatedAdminCounselingEventsRoute
  '/_authenticated/admin/counseling/reviews': typeof AuthenticatedAdminCounselingReviewsRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/counseling/college/$id': typeof AuthenticatedCounselingCollegeIdRoute
  '/_authenticated/counseling/resources/$slug': typeof AuthenticatedCounselingResourcesSlugRoute
  '/_authenticated/admin/content/': typeof AuthenticatedAdminContentIndexRoute
  '/_authenticated/admin/counseling/': typeof AuthenticatedAdminCounselingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/delete-account'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/counseling'
    | '/home'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/pyq'
    | '/search'
    | '/api/razorpay-webhook'
    | '/legal/$slug'
    | '/admin/activity'
    | '/admin/billing'
    | '/admin/counseling'
    | '/admin/legal'
    | '/admin/users'
    | '/coming-soon/$feature'
    | '/counseling/calendar'
    | '/counseling/choice-filling'
    | '/counseling/compare'
    | '/counseling/explorer'
    | '/counseling/predictor'
    | '/counseling/resources'
    | '/counseling/roadmap'
    | '/review/$attemptId'
    | '/subject/$slug'
    | '/test/$attemptId'
    | '/tests/new'
    | '/admin/'
    | '/counseling/'
    | '/admin/content/generate'
    | '/admin/content/import'
    | '/admin/counseling/articles'
    | '/admin/counseling/cutoffs'
    | '/admin/counseling/events'
    | '/admin/counseling/reviews'
    | '/admin/users/$id'
    | '/counseling/college/$id'
    | '/counseling/resources/$slug'
    | '/admin/content/'
    | '/admin/counseling/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/delete-account'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/home'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/pyq'
    | '/search'
    | '/api/razorpay-webhook'
    | '/legal/$slug'
    | '/admin/activity'
    | '/admin/billing'
    | '/admin/legal'
    | '/admin/users'
    | '/coming-soon/$feature'
    | '/counseling/calendar'
    | '/counseling/choice-filling'
    | '/counseling/compare'
    | '/counseling/explorer'
    | '/counseling/predictor'
    | '/counseling/resources'
    | '/counseling/roadmap'
    | '/review/$attemptId'
    | '/subject/$slug'
    | '/test/$attemptId'
    | '/tests/new'
    | '/admin'
    | '/counseling'
    | '/admin/content/generate'
    | '/admin/content/import'
    | '/admin/counseling/articles'
    | '/admin/counseling/cutoffs'
    | '/admin/counseling/events'
    | '/admin/counseling/reviews'
    | '/admin/users/$id'
    | '/counseling/college/$id'
    | '/counseling/resources/$slug'
    | '/admin/content'
    | '/admin/counseling'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/delete-account'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/counseling'
    | '/_authenticated/home'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/pricing'
    | '/_authenticated/profile'
    | '/_authenticated/pyq'
    | '/_authenticated/search'
    | '/api/razorpay-webhook'
    | '/legal/$slug'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/counseling'
    | '/_authenticated/admin/legal'
    | '/_authenticated/admin/users'
    | '/_authenticated/coming-soon/$feature'
    | '/_authenticated/counseling/calendar'
    | '/_authenticated/counseling/choice-filling'
    | '/_authenticated/counseling/compare'
    | '/_authenticated/counseling/explorer'
    | '/_authenticated/counseling/predictor'
    | '/_authenticated/counseling/resources'
    | '/_authenticated/counseling/roadmap'
    | '/_authenticated/review/$attemptId'
    | '/_authenticated/subject/$slug'
    | '/_authenticated/test/$attemptId'
    | '/_authenticated/tests/new'
    | '/_authenticated/admin/'
    | '/_authenticated/counseling/'
    | '/_authenticated/admin/content/generate'
    | '/_authenticated/admin/content/import'
    | '/_authenticated/admin/counseling/articles'
    | '/_authenticated/admin/counseling/cutoffs'
    | '/_authenticated/admin/counseling/events'
    | '/_authenticated/admin/counseling/reviews'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/counseling/college/$id'
    | '/_authenticated/counseling/resources/$slug'
    | '/_authenticated/admin/content/'
    | '/_authenticated/admin/counseling/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiRazorpayWebhookRoute: typeof ApiRazorpayWebhookRoute
  LegalSlugRoute: typeof LegalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay-webhook': {
      id: '/api/razorpay-webhook'
      path: '/api/razorpay-webhook'
      fullPath: '/api/razorpay-webhook'
      preLoaderRoute: typeof ApiRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pyq': {
      id: '/_authenticated/pyq'
      path: '/pyq'
      fullPath: '/pyq'
      preLoaderRoute: typeof AuthenticatedPyqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/counseling': {
      id: '/_authenticated/counseling'
      path: '/counseling'
      fullPath: '/counseling'
      preLoaderRoute: typeof AuthenticatedCounselingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/counseling/': {
      id: '/_authenticated/counseling/'
      path: '/'
      fullPath: '/counseling/'
      preLoaderRoute: typeof AuthenticatedCounselingIndexRouteImport
      parentRoute: typeof AuthenticatedCounselingRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/tests/new': {
      id: '/_authenticated/tests/new'
      path: '/tests/new'
      fullPath: '/tests/new'
      preLoaderRoute: typeof AuthenticatedTestsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/test/$attemptId': {
      id: '/_authenticated/test/$attemptId'
      path: '/test/$attemptId'
      fullPath: '/test/$attemptId'
      preLoaderRoute: typeof AuthenticatedTestAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subject/$slug': {
      id: '/_authenticated/subject/$slug'
      path: '/subject/$slug'
      fullPath: '/subject/$slug'
      preLoaderRoute: typeof AuthenticatedSubjectSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/$attemptId': {
      id: '/_authenticated/review/$attemptId'
      path: '/review/$attemptId'
      fullPath: '/review/$attemptId'
      preLoaderRoute: typeof AuthenticatedReviewAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/counseling/roadmap': {
      id: '/_authenticated/counseling/roadmap'
      path: '/roadmap'
      fullPath: '/counseling/roadmap'
      preLoaderRoute: typeof AuthenticatedCounselingRoadmapRouteImport
      parentRoute: typeof AuthenticatedCounselingRoute
    }
    '/_authenticated/counseling/resources': {
      id: '/_authenticated/counseling/resources'
      path: '/resources'
      fullPath: '/counseling/resources'
      preLoaderRoute: typeof AuthenticatedCounselingResourcesRouteImport
      parentRoute: typeof AuthenticatedCounselingRoute
    }
    '/_authenticated/counseling/predictor': {
      id: '/_authenticated/counseling/predictor'
      path: '/predictor'
      fullPath: '/counseling/predictor'
      preLoaderRoute: typeof AuthenticatedCounselingPredictorRouteImport
      parentRoute: typeof AuthenticatedCounselingRoute
    }
    '/_authenticated/counseling/explorer': {
      id: '/_authenticated/counseling/explorer'
      path: '/explorer'
      fullPath: '/counseling/explorer'
      preLoaderRoute: typeof AuthenticatedCounselingExplorerRouteImport
      parentRoute: typeof AuthenticatedCounselingRoute
    }
    '/_authenticated/counseling/compare': {
      id: '/_authenticated/counseling/compare'
      path: '/compare'
      fullPath: '/counseling/compare'
      preLoaderRoute: typeof AuthenticatedCounselingCompareRouteImport
      parentRoute: typeof AuthenticatedCounselingRoute
    }
    '/_authenticated/counseling/choice-filling': {
      id: '/_authenticated/counseling/choice-filling'
      path: '/choice-filling'
      fullPath: '/counseling/choice-filling'
      preLoaderRoute: typeof AuthenticatedCounselingChoiceFillingRouteImport
      parentRoute: typeof AuthenticatedCounselingRoute
    }
    '/_authenticated/counseling/calendar': {
      id: '/_authenticated/counseling/calendar'
      path: '/calendar'
      fullPath: '/counseling/calendar'
      preLoaderRoute: typeof AuthenticatedCounselingCalendarRouteImport
      parentRoute: typeof AuthenticatedCounselingRoute
    }
    '/_authenticated/coming-soon/$feature': {
      id: '/_authenticated/coming-soon/$feature'
      path: '/coming-soon/$feature'
      fullPath: '/coming-soon/$feature'
      preLoaderRoute: typeof AuthenticatedComingSoonFeatureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/legal': {
      id: '/_authenticated/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AuthenticatedAdminLegalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/counseling': {
      id: '/_authenticated/admin/counseling'
      path: '/counseling'
      fullPath: '/admin/counseling'
      preLoaderRoute: typeof AuthenticatedAdminCounselingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/counseling/': {
      id: '/_authenticated/admin/counseling/'
      path: '/'
      fullPath: '/admin/counseling/'
      preLoaderRoute: typeof AuthenticatedAdminCounselingIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCounselingRoute
    }
    '/_authenticated/admin/content/': {
      id: '/_authenticated/admin/content/'
      path: '/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AuthenticatedAdminContentIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/counseling/resources/$slug': {
      id: '/_authenticated/counseling/resources/$slug'
      path: '/$slug'
      fullPath: '/counseling/resources/$slug'
      preLoaderRoute: typeof AuthenticatedCounselingResourcesSlugRouteImport
      parentRoute: typeof AuthenticatedCounselingResourcesRoute
    }
    '/_authenticated/counseling/college/$id': {
      id: '/_authenticated/counseling/college/$id'
      path: '/college/$id'
      fullPath: '/counseling/college/$id'
      preLoaderRoute: typeof AuthenticatedCounselingCollegeIdRouteImport
      parentRoute: typeof AuthenticatedCounselingRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/counseling/reviews': {
      id: '/_authenticated/admin/counseling/reviews'
      path: '/reviews'
      fullPath: '/admin/counseling/reviews'
      preLoaderRoute: typeof AuthenticatedAdminCounselingReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminCounselingRoute
    }
    '/_authenticated/admin/counseling/events': {
      id: '/_authenticated/admin/counseling/events'
      path: '/events'
      fullPath: '/admin/counseling/events'
      preLoaderRoute: typeof AuthenticatedAdminCounselingEventsRouteImport
      parentRoute: typeof AuthenticatedAdminCounselingRoute
    }
    '/_authenticated/admin/counseling/cutoffs': {
      id: '/_authenticated/admin/counseling/cutoffs'
      path: '/cutoffs'
      fullPath: '/admin/counseling/cutoffs'
      preLoaderRoute: typeof AuthenticatedAdminCounselingCutoffsRouteImport
      parentRoute: typeof AuthenticatedAdminCounselingRoute
    }
    '/_authenticated/admin/counseling/articles': {
      id: '/_authenticated/admin/counseling/articles'
      path: '/articles'
      fullPath: '/admin/counseling/articles'
      preLoaderRoute: typeof AuthenticatedAdminCounselingArticlesRouteImport
      parentRoute: typeof AuthenticatedAdminCounselingRoute
    }
    '/_authenticated/admin/content/import': {
      id: '/_authenticated/admin/content/import'
      path: '/content/import'
      fullPath: '/admin/content/import'
      preLoaderRoute: typeof AuthenticatedAdminContentImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content/generate': {
      id: '/_authenticated/admin/content/generate'
      path: '/content/generate'
      fullPath: '/admin/content/generate'
      preLoaderRoute: typeof AuthenticatedAdminContentGenerateRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminCounselingRouteChildren {
  AuthenticatedAdminCounselingArticlesRoute: typeof AuthenticatedAdminCounselingArticlesRoute
  AuthenticatedAdminCounselingCutoffsRoute: typeof AuthenticatedAdminCounselingCutoffsRoute
  AuthenticatedAdminCounselingEventsRoute: typeof AuthenticatedAdminCounselingEventsRoute
  AuthenticatedAdminCounselingReviewsRoute: typeof AuthenticatedAdminCounselingReviewsRoute
  AuthenticatedAdminCounselingIndexRoute: typeof AuthenticatedAdminCounselingIndexRoute
}

const AuthenticatedAdminCounselingRouteChildren: AuthenticatedAdminCounselingRouteChildren =
  {
    AuthenticatedAdminCounselingArticlesRoute:
      AuthenticatedAdminCounselingArticlesRoute,
    AuthenticatedAdminCounselingCutoffsRoute:
      AuthenticatedAdminCounselingCutoffsRoute,
    AuthenticatedAdminCounselingEventsRoute:
      AuthenticatedAdminCounselingEventsRoute,
    AuthenticatedAdminCounselingReviewsRoute:
      AuthenticatedAdminCounselingReviewsRoute,
    AuthenticatedAdminCounselingIndexRoute:
      AuthenticatedAdminCounselingIndexRoute,
  }

const AuthenticatedAdminCounselingRouteWithChildren =
  AuthenticatedAdminCounselingRoute._addFileChildren(
    AuthenticatedAdminCounselingRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminCounselingRoute: typeof AuthenticatedAdminCounselingRouteWithChildren
  AuthenticatedAdminLegalRoute: typeof AuthenticatedAdminLegalRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminContentGenerateRoute: typeof AuthenticatedAdminContentGenerateRoute
  AuthenticatedAdminContentImportRoute: typeof AuthenticatedAdminContentImportRoute
  AuthenticatedAdminContentIndexRoute: typeof AuthenticatedAdminContentIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminCounselingRoute:
    AuthenticatedAdminCounselingRouteWithChildren,
  AuthenticatedAdminLegalRoute: AuthenticatedAdminLegalRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminContentGenerateRoute:
    AuthenticatedAdminContentGenerateRoute,
  AuthenticatedAdminContentImportRoute: AuthenticatedAdminContentImportRoute,
  AuthenticatedAdminContentIndexRoute: AuthenticatedAdminContentIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCounselingResourcesRouteChildren {
  AuthenticatedCounselingResourcesSlugRoute: typeof AuthenticatedCounselingResourcesSlugRoute
}

const AuthenticatedCounselingResourcesRouteChildren: AuthenticatedCounselingResourcesRouteChildren =
  {
    AuthenticatedCounselingResourcesSlugRoute:
      AuthenticatedCounselingResourcesSlugRoute,
  }

const AuthenticatedCounselingResourcesRouteWithChildren =
  AuthenticatedCounselingResourcesRoute._addFileChildren(
    AuthenticatedCounselingResourcesRouteChildren,
  )

interface AuthenticatedCounselingRouteChildren {
  AuthenticatedCounselingCalendarRoute: typeof AuthenticatedCounselingCalendarRoute
  AuthenticatedCounselingChoiceFillingRoute: typeof AuthenticatedCounselingChoiceFillingRoute
  AuthenticatedCounselingCompareRoute: typeof AuthenticatedCounselingCompareRoute
  AuthenticatedCounselingExplorerRoute: typeof AuthenticatedCounselingExplorerRoute
  AuthenticatedCounselingPredictorRoute: typeof AuthenticatedCounselingPredictorRoute
  AuthenticatedCounselingResourcesRoute: typeof AuthenticatedCounselingResourcesRouteWithChildren
  AuthenticatedCounselingRoadmapRoute: typeof AuthenticatedCounselingRoadmapRoute
  AuthenticatedCounselingIndexRoute: typeof AuthenticatedCounselingIndexRoute
  AuthenticatedCounselingCollegeIdRoute: typeof AuthenticatedCounselingCollegeIdRoute
}

const AuthenticatedCounselingRouteChildren: AuthenticatedCounselingRouteChildren =
  {
    AuthenticatedCounselingCalendarRoute: AuthenticatedCounselingCalendarRoute,
    AuthenticatedCounselingChoiceFillingRoute:
      AuthenticatedCounselingChoiceFillingRoute,
    AuthenticatedCounselingCompareRoute: AuthenticatedCounselingCompareRoute,
    AuthenticatedCounselingExplorerRoute: AuthenticatedCounselingExplorerRoute,
    AuthenticatedCounselingPredictorRoute:
      AuthenticatedCounselingPredictorRoute,
    AuthenticatedCounselingResourcesRoute:
      AuthenticatedCounselingResourcesRouteWithChildren,
    AuthenticatedCounselingRoadmapRoute: AuthenticatedCounselingRoadmapRoute,
    AuthenticatedCounselingIndexRoute: AuthenticatedCounselingIndexRoute,
    AuthenticatedCounselingCollegeIdRoute:
      AuthenticatedCounselingCollegeIdRoute,
  }

const AuthenticatedCounselingRouteWithChildren =
  AuthenticatedCounselingRoute._addFileChildren(
    AuthenticatedCounselingRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCounselingRoute: typeof AuthenticatedCounselingRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPyqRoute: typeof AuthenticatedPyqRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedComingSoonFeatureRoute: typeof AuthenticatedComingSoonFeatureRoute
  AuthenticatedReviewAttemptIdRoute: typeof AuthenticatedReviewAttemptIdRoute
  AuthenticatedSubjectSlugRoute: typeof AuthenticatedSubjectSlugRoute
  AuthenticatedTestAttemptIdRoute: typeof AuthenticatedTestAttemptIdRoute
  AuthenticatedTestsNewRoute: typeof AuthenticatedTestsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCounselingRoute: AuthenticatedCounselingRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPyqRoute: AuthenticatedPyqRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedComingSoonFeatureRoute: AuthenticatedComingSoonFeatureRoute,
  AuthenticatedReviewAttemptIdRoute: AuthenticatedReviewAttemptIdRoute,
  AuthenticatedSubjectSlugRoute: AuthenticatedSubjectSlugRoute,
  AuthenticatedTestAttemptIdRoute: AuthenticatedTestAttemptIdRoute,
  AuthenticatedTestsNewRoute: AuthenticatedTestsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiRazorpayWebhookRoute: ApiRazorpayWebhookRoute,
  LegalSlugRoute: LegalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
